### PR TITLE
Don't include deps in views, ignore conflicts

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Our view updates were failing due to conflicts. This PR restricts what gets included, and also adds the `-i` flag to ignore conflicts in case they do occur.

**Review by vsoch — APPROVED** [review]
This looks good! My only suggestion would be to use the full flag name (if there is one) so a future reader not familiar with spack can more easily understand.

**Comment by davidbeckingsale** [comment]
> This looks good! My only suggestion would be to use the full flag name (if there is one) so a future reader not familiar with spack can more easily understand.

Good idea, will fix.

**Comment by vsoch** [comment]
That's now perfect! I'll watch this and merge when all builds pass (relevant to the changes)

**Review by vsoch — APPROVED** [review]

**Pull request merged**
