### PR TITLE
start of work to add ubuntu-nvidia

### PR DESCRIPTION
**Pull request by vsoch**
we are going to need uptodate to be able to only build given some change in a file

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Can we try using Spack to install cuda on top of one of our ubuntu images? (I am happy to look at that)

**Comment by vsoch** [comment]
oh yeah sure, I can add that one. What versions / patterns are you interested in? Right now I'm just copying what I see in axom-docker, but I can definitely focus ona nother set. For the PR here I need to add functionality to uptodate to only build changed files, hence why we are building too many things right now.

**Comment by davidbeckingsale** [comment]
I'll put up a PR and see if I can figure everything out  😄

**Comment by vsoch** [comment]
haha okay, but it's going to build all those clang images too (3+ hours) so we might need the functionality to only build changed files sooner than I anticipated!

**Comment by davidbeckingsale** [comment]
Okay, I'll wait - I can test out the template Dockerfile locally and make sure it's going to work.

**Comment by vsoch** [comment]
okay this looks like a good start! If there is an empty matrix there is a warning in the action, but as we see, it doesn't fail! Let's merge and move on to the next one.

**Pull request merged**
